### ISSUE TITLE
[BUG] docker login is failing.

### ISSUE THREAD

**Issue by pwhelan** [chronosphereio/calyptia-plugin#67]
Did we ever look at this @patrick-stephens or @celalettin1286  during the move to chronosphere? Was it failing before?

**Comment by patrick-stephens** [comment]
It's probably missing the secret that was an org one before. @matthiasr is working

**Comment by patrick-stephens** [comment]
The actions are all out of date too, it seems dependabot PRs are not being merged...

**Comment by patrick-stephens** [comment]
@pwhelan which login is failing, CI looks fine: https://github.com/chronosphereio/calyptia-plugin/actions/runs/8628051664/job/23649284675

I checked the workflows and they're using defined secrets.
https://github.com/chronosphereio/calyptia-plugin/blob/585f27a40f04f4809aa71c8d2cb063ce76284fc9/.github/workflows/ci.yaml#L43-L48


We need to remove codecov as that is no longer used.
